Repository linode/linode_api4-python, pull requests merged in 2024-05, with the labels that each got.

#396 new: Add support for Placement Groups
  docs/linode_api4/linode_client.rst
  docs/linode_api4/objects/models.rst
  linode_api4/groups/__init__.py
  linode_api4/groups/linode.py
  linode_api4/groups/placement.py
  linode_api4/linode_client.py
  linode_api4/objects/__init__.py
  linode_api4/objects/linode.py
  linode_api4/objects/placement.py
  linode_api4/objects/region.py
  linode_api4/objects/serializable.py
  test/fixtures/linode_instances.json
  test/fixtures/placement_groups.json
  test/fixtures/placement_groups_123.json
  test/fixtures/regions.json
  test/integration/conftest.py
  test/integration/models/test_placement.py
  test/unit/objects/linode_test.py
  test/unit/objects/placement_test.py
  test/unit/objects/region_test.py
Labels: new-feature

#405 CI: replace test execution handler with conditional
  .github/workflows/e2e-test.yml
  Makefile
Labels: repo-ci-improvement

#406 new: Add support for LKE Control Plane ACLs
  linode_api4/groups/lke.py
  linode_api4/objects/lke.py
  linode_api4/objects/serializable.py
  linode_api4/objects/vpc.py
  test/fixtures/lke_clusters_18881_control__plane__acl.json
  test/integration/models/lke/test_lke.py
  test/unit/fixtures.py
  test/unit/objects/lke_test.py
  test/unit/objects/serializable_test.py
Labels: new-feature

#407 test: Fix failure in oauth test due to missing fixture initialization
  Makefile
  test/integration/login_client/test_login_client.py
Labels: testing
