Repository linode/linode_api4-python, pull requests merged in 2024-11, with the labels that each got.

#471 test: Allow integration and unit tests to run against EOL or desired python version
  .github/workflows/e2e-test.yml
  .github/workflows/main.yml
Labels: testing

#473 Configure default Python version using integration-tests job environment
  .github/workflows/e2e-test.yml
Labels: repo-ci-improvement

#474 test: Update warm resizing test case
  test/integration/models/linode/test_linode.py
Labels: testing

#475 CI: Set token for security jobs in e2e test workflow
  .github/workflows/e2e-test.yml
Labels: repo-ci-improvement

#472 Release v5.24.0
  .github/workflows/e2e-test-pr.yml
  .github/workflows/e2e-test.yml
  .github/workflows/main.yml
  .github/workflows/release-notify-slack.yml
  linode_api4/errors.py
  linode_api4/groups/lke.py
  linode_api4/groups/networking.py
  linode_api4/groups/nodebalancer.py
  linode_api4/groups/volume.py
  linode_api4/linode_client.py
  linode_api4/login_client.py
  linode_api4/objects/account.py
  linode_api4/objects/lke.py
  linode_api4/objects/networking.py
  linode_api4/objects/nodebalancer.py
  linode_api4/objects/support.py
  linode_api4/objects/volume.py
  test/integration/linode_client/test_errors.py
  test/integration/models/linode/test_linode.py
  test/unit/errors_test.py
Labels: ignore-for-release

#477 Support `migrations` under placement group
  linode_api4/objects/placement.py
  test/fixtures/placement_groups.json
  test/fixtures/placement_groups_123.json
  test/integration/models/placement/test_placement.py
  test/unit/objects/placement_test.py
Labels: improvement
