Repository linode/linode_api4-python, pull requests merged in 2024-10, with the labels that each got.

#462 Resolve circular imports and restore top-level imports
  linode_api4/objects/linode.py
  linode_api4/objects/networking.py
  linode_api4/objects/nodebalancer.py
  linode_api4/objects/volume.py
  linode_api4/objects/vpc.py
Labels: improvement

#453 Added support for Block Storage Encryption
  linode_api4/groups/volume.py
  linode_api4/objects/linode.py
  linode_api4/objects/volume.py
  test/fixtures/volumes.json
  test/integration/conftest.py
  test/integration/models/linode/test_linode.py
  test/integration/models/volume/test_volume.py
  test/unit/linode_client_test.py
  test/unit/objects/volume_test.py
Labels: new-feature

#466 Add include_none_values ClassVar to JSONObject; apply to response-only classes
  linode_api4/objects/image.py
  linode_api4/objects/lke.py
  linode_api4/objects/serializable.py
  test/unit/objects/serializable_test.py
Labels: bugfix

#465 Release v5.23.0
  .github/workflows/e2e-test.yml
  .github/workflows/nightly-smoke-tests.yml
  .gitignore
  .pylintrc
  linode_api4/groups/image.py
  linode_api4/groups/polling.py
  linode_api4/groups/volume.py
  linode_api4/linode_client.py
  linode_api4/objects/account.py
  linode_api4/objects/image.py
  linode_api4/objects/linode.py
  linode_api4/objects/lke.py
  linode_api4/objects/networking.py
  linode_api4/objects/nodebalancer.py
  linode_api4/objects/region.py
  linode_api4/objects/serializable.py
  linode_api4/objects/volume.py
  linode_api4/objects/vpc.py
  linode_api4/polling.py
  pyproject.toml
  test/fixtures/volumes.json
  test/integration/conftest.py
  test/integration/helpers.py
  test/integration/linode_client/test_linode_client.py
  test/integration/login_client/test_login_client.py
  test/integration/models/account/test_account.py
  test/integration/models/firewall/test_firewall.py
  test/integration/models/image/test_image.py
  test/integration/models/linode/test_linode.py
  test/integration/models/lke/test_lke.py
  test/integration/models/networking/test_networking.py
  test/integration/models/nodebalancer/test_nodebalancer.py
  test/integration/models/object_storage/test_obj.py
  test/integration/models/placement/test_placement.py
  test/integration/models/profile/test_profile.py
  test/integration/models/volume/test_volume.py
  test/integration/models/vpc/test_vpc.py
  test/unit/linode_client_test.py
  test/unit/objects/account_test.py
  test/unit/objects/image_test.py
  test/unit/objects/serializable_test.py
  test/unit/objects/volume_test.py
  tox.ini
Labels: ignore-for-release

#467 Improve ApiError message formatting; add `response` field to ApiError and UnexpectedResponseError
  linode_api4/errors.py
  linode_api4/linode_client.py
  linode_api4/login_client.py
  linode_api4/objects/account.py
  linode_api4/objects/support.py
  test/integration/linode_client/test_errors.py
  test/unit/errors_test.py
Labels: improvement

#469 CI: Notify slack channel on releases
  .github/workflows/release-notify-slack.yml
Labels: repo-ci-improvement
