Repository linode/linode_api4-python, pull requests merged in 2024-07, with the labels that each got.

#426 Update OBJ Group and Objects for MultiCluster Object Storage API Changes
  linode_api4/groups/object_storage.py
  linode_api4/objects/object_storage.py
  test/fixtures/object-storage_buckets_us-east-1_example-bucket.json
  test/fixtures/object-storage_keys.json
  test/integration/models/object_storage/test_obj.py
  test/unit/groups/__init__.py
  test/unit/groups/object_storage_test.py
  test/unit/linode_client_test.py
  test/unit/objects/object_storage_test.py
Labels: breaking-change

#428 new: Support Image Gen2 functionalities
  linode_api4/groups/image.py
  linode_api4/linode_client.py
  linode_api4/objects/image.py
  test/fixtures/images.json
  test/fixtures/images_private_123_regions.json
  test/fixtures/images_upload.json
  test/integration/linode_client/test_linode_client.py
  test/integration/models/image/test_image.py
  test/unit/linode_client_test.py
  test/unit/objects/image_test.py
Labels: new-feature

#431 test: Add error handling in e2e_cloud_firewall fixture
  test/integration/conftest.py
Labels: testing

#416 project: MultiCluster Object Storage
  linode_api4/groups/object_storage.py
  linode_api4/objects/object_storage.py
  pyproject.toml
  test/fixtures/object-storage_buckets_us-east-1_example-bucket.json
  test/fixtures/object-storage_keys.json
  test/integration/models/object_storage/test_obj.py
  test/unit/groups/__init__.py
  test/unit/groups/object_storage_test.py
  test/unit/linode_client_test.py
  test/unit/objects/object_storage_test.py
Labels: new-feature

#429 test: Add missing integration tests to improve coverage for identified gaps
  test/integration/conftest.py
  test/integration/linode_client/test_linode_client.py
  test/integration/login_client/test_login_client.py
  test/integration/models/account/test_account.py
  test/integration/models/lke/test_lke.py
  test/integration/models/longview/test_longview.py
  test/integration/models/objectstorage/test_obj_storage.py
  test/integration/models/profile/test_profile.py
Labels: testing

#430 test: Add option to run integration tests against minimal test account without any special customer tags
  .github/workflows/e2e-test.yml
Labels: testing

#432 new: Add support for Linode Disk Encryption (#413)
  linode_api4/groups/linode.py
  linode_api4/objects/linode.py
  linode_api4/objects/lke.py
  test/fixtures/linode_instances.json
  test/fixtures/linode_instances_123_disks.json
  test/fixtures/linode_instances_123_disks_12345_clone.json
  test/fixtures/lke_clusters_18881_nodes_123456.json
  test/fixtures/lke_clusters_18881_pools_456.json
  test/integration/helpers.py
  test/integration/models/linode/test_linode.py
  test/integration/models/lke/test_lke.py
  test/unit/objects/linode_test.py
  test/unit/objects/lke_test.py
Labels: new-feature, do-not-merge

#435 Revert "new: Add support for Linode Disk Encryption (#413)"
  linode_api4/groups/linode.py
  linode_api4/objects/linode.py
  linode_api4/objects/lke.py
  test/fixtures/linode_instances.json
  test/fixtures/linode_instances_123_disks.json
  test/fixtures/linode_instances_123_disks_12345_clone.json
  test/fixtures/lke_clusters_18881_nodes_123456.json
  test/fixtures/lke_clusters_18881_pools_456.json
  test/integration/helpers.py
  test/integration/models/linode/test_linode.py
  test/integration/models/lke/test_lke.py
  test/unit/objects/linode_test.py
  test/unit/objects/lke_test.py
Labels: ignore-for-release

#438 test: Add submodule checkout in cross release test workflow
  .github/workflows/release-cross-repo-test.yml
Labels: testing

#437 ref: PG affinity_type, is_strict -> placement_group_type, placement_group_policy
  linode_api4/groups/placement.py
  linode_api4/objects/placement.py
  test/fixtures/linode_instances.json
  test/fixtures/placement_groups.json
  test/fixtures/placement_groups_123.json
  test/integration/conftest.py
  test/unit/objects/linode_test.py
  test/unit/objects/placement_test.py
Labels: improvement, breaking-change

#440 Add project label
  .github/labels.yml
  .github/release.yml
Labels: repo-ci-improvement

#439 Update api doc urls to point to techdocs
  README.rst
  docs/index.rst
  linode_api4/groups/account.py
  linode_api4/groups/beta.py
  linode_api4/groups/database.py
  linode_api4/groups/domain.py
  linode_api4/groups/image.py
  linode_api4/groups/linode.py
  linode_api4/groups/lke.py
  linode_api4/groups/longview.py
  linode_api4/groups/networking.py
  linode_api4/groups/nodebalancer.py
  linode_api4/groups/object_storage.py
  linode_api4/groups/polling.py
  linode_api4/groups/profile.py
  linode_api4/groups/region.py
  linode_api4/groups/support.py
  linode_api4/groups/tag.py
  linode_api4/groups/volume.py
  linode_api4/objects/account.py
  linode_api4/objects/beta.py
  linode_api4/objects/database.py
  linode_api4/objects/domain.py
  linode_api4/objects/image.py
  linode_api4/objects/linode.py
  linode_api4/objects/lke.py
  linode_api4/objects/longview.py
  linode_api4/objects/networking.py
  linode_api4/objects/nodebalancer.py
  linode_api4/objects/object_storage.py
  linode_api4/objects/profile.py
  linode_api4/objects/region.py
  linode_api4/objects/support.py
  linode_api4/objects/tag.py
  linode_api4/objects/volume.py
  pyproject.toml
Labels: documentation

#436 project: Linode Disk Encryption (re-apply)
  linode_api4/groups/linode.py
  linode_api4/objects/linode.py
  linode_api4/objects/lke.py
  test/fixtures/linode_instances.json
  test/fixtures/linode_instances_123_disks.json
  test/fixtures/linode_instances_123_disks_12345_clone.json
  test/fixtures/lke_clusters_18881_nodes_123456.json
  test/fixtures/lke_clusters_18881_pools_456.json
  test/integration/helpers.py
  test/integration/models/linode/test_linode.py
  test/integration/models/lke/test_lke.py
  test/unit/objects/linode_test.py
  test/unit/objects/lke_test.py
Labels: new-feature, ignore-for-release

#444 test: Temporarily disable LDE integration tests
  test/integration/conftest.py
  test/integration/models/linode/test_linode.py
  test/integration/models/lke/test_lke.py
Labels: testing

#441 fix: Resolve error when creating EventError(...) with message=None
  linode_api4/polling.py
  test/unit/objects/polling_test.py
Labels: bugfix
