Repository linode/linode_api4-python, pull requests merged in 2024-08, with the labels that each got.

#447 doc: Replace outdated API documentation TODOs with URLs
  linode_api4/groups/account.py
  linode_api4/groups/placement.py
  linode_api4/groups/vpc.py
  linode_api4/objects/account.py
  linode_api4/objects/linode.py
  linode_api4/objects/placement.py
  linode_api4/objects/vpc.py
Labels: documentation

#445 Project: Image Services Gen2
  linode_api4/groups/image.py
  linode_api4/linode_client.py
  linode_api4/objects/image.py
  test/fixtures/images.json
  test/fixtures/images_private_123_regions.json
  test/fixtures/images_upload.json
  test/integration/conftest.py
  test/integration/linode_client/test_linode_client.py
  test/integration/models/image/test_image.py
  test/unit/linode_client_test.py
  test/unit/objects/image_test.py
Labels: project

#448 new: Add support for LKE node pool labels & taints
  linode_api4/groups/lke.py
  linode_api4/objects/base.py
  linode_api4/objects/lke.py
  test/fixtures/lke_clusters_18881_pools_456.json
  test/integration/models/lke/test_lke.py
  test/unit/objects/lke_test.py
Labels: new-feature

#450 Increase max wait time for `test_linode_resize`
  test/integration/models/linode/test_linode.py
Labels: testing

#451 Release v5.21.0
  linode_api4/groups/lke.py
  linode_api4/objects/base.py
  linode_api4/objects/lke.py
  test/fixtures/lke_clusters_18881_pools_456.json
  test/integration/models/linode/test_linode.py
  test/integration/models/lke/test_lke.py
  test/unit/objects/lke_test.py
Labels: ignore-for-release
