Repository linode/linode_api4-python, pull requests merged in 2024-04, with the labels that each got.

#386 new: Add site_type to `Region`
  linode_api4/objects/region.py
  test/fixtures/regions.json
  test/integration/linode_client/test_linode_client.py
  test/unit/linode_client_test.py
  test/unit/objects/region_test.py
Labels: enhancement

#389 Serialize `Base` objects in `MappedObject`
  linode_api4/objects/base.py
  test/fixtures/testmappedobj1.json
  test/unit/objects/mapped_object_test.py
Labels: enhancement, breaking-change

#393 CI improvement: add integration workflow for main and dev
  .github/workflows/e2e-test.yml
Labels: repo-ci-improvement

#394 test: address intermittent test failures
  test/integration/models/test_database.py
  test/integration/models/test_linode.py
  test/integration/models/test_lke.py
Labels: testing

#395 new: Add `available` field to AccountAvailability class
  linode_api4/groups/account.py
  linode_api4/objects/account.py
  test/fixtures/account_availability.json
  test/fixtures/account_availability_us-east.json
  test/unit/objects/account_test.py
Labels: new-feature

#400 fix: Always load object values when converting MappedObjects to dict
  linode_api4/objects/base.py
  linode_api4/objects/dbase.py
  linode_api4/objects/object_storage.py
  test/unit/objects/linode_test.py
Labels: bugfix

#399 Serialize `JSONObject` in `MappedObject`
  linode_api4/objects/base.py
  test/unit/objects/mapped_object_test.py
Labels: enhancement

#403 test: Add new tests for Oauth and Login Client
  test/integration/login_client/test_login_client.py
  test/integration/models/account/test_account.py
Labels: testing
