Repository linode/linode_api4-python, pull requests merged in 2024-06, with the labels that each got.

#410 Add warnings to deprecated OBJ API usage
  linode_api4/groups/obj.py
  linode_api4/groups/object_storage.py
  linode_api4/objects/object_storage.py
  pyproject.toml
Labels: improvement

#414 Turn on `remove-all-unused-imports` in for autoflake
  linode_api4/groups/account.py
  linode_api4/groups/linode.py
  linode_api4/groups/polling.py
  linode_api4/linode_client.py
  linode_api4/objects/region.py
  linode_api4/objects/tag.py
  pyproject.toml
  test/integration/linode_client/test_linode_client.py
  test/integration/models/linode/test_linode.py
  test/integration/models/lke/test_lke.py
  test/integration/models/tag/test_tag.py
  test/unit/objects/region_test.py
  test/unit/objects/vpc_test.py
Labels: breaking-change

#408 test: Add Linode Cloud Firewall for integration tests
  test/integration/conftest.py
  test/integration/linode_client/test_linode_client.py
  test/integration/models/linode/test_linode.py
  test/integration/models/nodebalancer/test_nodebalancer.py
  test/integration/models/volume/test_volume.py
Labels: testing

#415 doc: Add note about limited LKE ACL availability
  linode_api4/objects/lke.py
Labels: documentation

#413 new: Add support for Linode Disk Encryption
  linode_api4/groups/linode.py
  linode_api4/objects/linode.py
  linode_api4/objects/lke.py
  linode_api4/objects/serializable.py
  test/fixtures/linode_instances.json
  test/fixtures/linode_instances_123_disks.json
  test/fixtures/linode_instances_123_disks_12345_clone.json
  test/fixtures/lke_clusters_18881_nodes_123456.json
  test/fixtures/lke_clusters_18881_pools_456.json
  test/integration/helpers.py
  test/integration/models/linode/test_linode.py
  test/integration/models/lke/test_lke.py
  test/unit/objects/linode_test.py
  test/unit/objects/lke_test.py
Labels: new-feature

#417 Cleanup duplicated `ObjectStorageGroup`
  linode_api4/groups/obj.py
Labels: improvement

#418 test: Add Calico Inbound and Outbound policies to LKE nodes for E2E
  .github/workflows/e2e-test-pr.yml
  .github/workflows/e2e-test.yml
  scripts/lke-policy.yaml
  scripts/lke_calico_rules_e2e.sh
Labels: testing

#422 doc: Add Placement Groups LA disclaimer
  linode_api4/groups/placement.py
  linode_api4/objects/placement.py
Labels: documentation

#424 project: VM Placement
  docs/linode_api4/linode_client.rst
  docs/linode_api4/objects/models.rst
  linode_api4/groups/__init__.py
  linode_api4/groups/linode.py
  linode_api4/groups/placement.py
  linode_api4/linode_client.py
  linode_api4/objects/__init__.py
  linode_api4/objects/linode.py
  linode_api4/objects/placement.py
  linode_api4/objects/region.py
  test/fixtures/linode_instances.json
  test/fixtures/placement_groups.json
  test/fixtures/placement_groups_123.json
  test/fixtures/regions.json
  test/integration/conftest.py
  test/integration/models/placement/test_placement.py
  test/unit/objects/linode_test.py
  test/unit/objects/placement_test.py
  test/unit/objects/region_test.py
Labels: new-feature
