Repository linode/linode_api4-python, pull requests merged in 2024-12, with the labels that each got.

#478 doc: Remove Image Services Gen2 LA notice
  linode_api4/objects/image.py
Labels: documentation

#481 test: Update duplicate label in placement group test
  test/integration/models/placement/test_placement.py
Labels: testing

#484 Make use of `_flatten_request_body_recursive(...)` wherever possible
  linode_api4/groups/image.py
  linode_api4/groups/linode.py
  linode_api4/groups/volume.py
  linode_api4/objects/linode.py
  linode_api4/objects/volume.py
Labels: improvement
