Repository linode/linode_api4-python, pull requests merged in 2025-04, with the labels that each got.

#530 Update test region capability for LDE
  test/integration/login_client/test_login_client.py
  test/integration/models/domain/test_domain.py
  test/integration/models/linode/test_linode.py
  test/integration/models/lke/test_lke.py
Labels: testing

#529 Enhanced Interfaces: Add support for Firewall templates
  linode_api4/groups/networking.py
  linode_api4/objects/networking.py
  test/fixtures/networking_firewalls_templates.json
  test/fixtures/networking_firewalls_templates_public.json
  test/fixtures/networking_firewalls_templates_vpc.json
  test/integration/models/firewall/test_firewall_templates.py
  test/unit/groups/networking_test.py
  test/unit/objects/firewall_test.py
Labels: new-feature

#525 Enhanced Interfaces: Add account-related fields
  linode_api4/objects/account.py
  test/fixtures/account.json
  test/fixtures/account_settings.json
  test/integration/models/account/test_account.py
  test/unit/linode_client_test.py
  test/unit/objects/account_test.py
Labels: new-feature

#531 Support Object Storage Quota Limits Visibility
  linode_api4/groups/object_storage.py
  linode_api4/objects/object_storage.py
  test/fixtures/object-storage_quotas.json
  test/fixtures/object-storage_quotas_obj-objects-us-ord-1.json
  test/fixtures/object-storage_quotas_obj-objects-us-ord-1_usage.json
  test/unit/objects/object_storage_test.py
Labels: new-feature

#526 Enhanced Interfaces: Implement endpoints & fields related to VPCs and non-interface networking
  linode_api4/groups/networking.py
  linode_api4/objects/networking.py
  linode_api4/objects/vpc.py
  test/fixtures/networking_firewalls_123_devices.json
  test/fixtures/networking_firewalls_123_devices_456.json
  test/fixtures/networking_firewalls_settings.json
  test/fixtures/networking_ips_127.0.0.1.json
  test/fixtures/regions.json
  test/fixtures/vpcs_123456_subnets.json
  test/fixtures/vpcs_123456_subnets_789.json
  test/integration/linode_client/test_linode_client.py
  test/integration/models/networking/test_networking.py
  test/unit/linode_client_test.py
  test/unit/objects/firewall_test.py
  test/unit/objects/networking_test.py
  test/unit/objects/region_test.py
  test/unit/objects/vpc_test.py
Labels: new-feature

#524 Implement support for VPC Dual Stack
  linode_api4/groups/vpc.py
  linode_api4/objects/linode.py
  linode_api4/objects/networking.py
  linode_api4/objects/vpc.py
  test/fixtures/linode_instances_123_configs.json
  test/fixtures/linode_instances_123_configs_456789.json
  test/fixtures/linode_instances_123_configs_456789_interfaces.json
  test/fixtures/linode_instances_123_configs_456789_interfaces_123.json
  test/fixtures/vpcs.json
  test/fixtures/vpcs_123456.json
  test/fixtures/vpcs_123456_ips.json
  test/fixtures/vpcs_123456_subnets.json
  test/fixtures/vpcs_123456_subnets_789.json
  test/fixtures/vpcs_ips.json
  test/unit/objects/linode_test.py
  test/unit/objects/vpc_test.py
Labels: new-feature

#539 Update obj test region
  test/integration/models/object_storage/test_obj.py
Labels: testing

#537 Release 5.29.1
  .github/workflows/labeler.yml
  linode_api4/objects/account.py
  linode_api4/objects/base.py
  linode_api4/objects/linode.py
  linode_api4/objects/serializable.py
  test/integration/login_client/test_login_client.py
  test/integration/models/domain/test_domain.py
  test/integration/models/linode/test_linode.py
  test/integration/models/lke/test_lke.py
  test/integration/models/object_storage/test_obj.py
  test/unit/objects/serializable_test.py
Labels: ignore-for-release
