Repository linode/linode_api4-python, pull requests merged in 2025-09, with the labels that each got.

#590 Updated incorrect documentation link for maintenance policies
  linode_api4/groups/maintenance.py
Labels: documentation

#591 Resolve various integration test failures
  test/integration/filters/fixtures.py
  test/integration/models/image/test_image.py
  test/integration/models/linode/test_linode.py
  test/integration/models/lke/test_lke.py
  test/integration/models/networking/test_networking.py
  test/integration/models/nodebalancer/test_nodebalancer.py
Labels: testing

#593 Disable image tests in no-osl-1
  test/integration/models/image/test_image.py
Labels: testing

#581 Made `longview_subscription` immutable in Account Settings
  linode_api4/objects/account.py
Labels: breaking-change

#540 Project: Linode Interfaces
  linode_api4/groups/linode.py
  linode_api4/groups/networking.py
  linode_api4/objects/__init__.py
  linode_api4/objects/account.py
  linode_api4/objects/base.py
  linode_api4/objects/linode.py
  linode_api4/objects/linode_interfaces.py
  linode_api4/objects/networking.py
  linode_api4/objects/serializable.py
  linode_api4/objects/vpc.py
  test/fixtures/account.json
  test/fixtures/account_settings.json
  test/fixtures/linode_instances.json
  test/fixtures/linode_instances_124.json
  test/fixtures/linode_instances_124_interfaces.json
  test/fixtures/linode_instances_124_interfaces_123.json
  test/fixtures/linode_instances_124_interfaces_123_firewalls.json
  test/fixtures/linode_instances_124_interfaces_456.json
  test/fixtures/linode_instances_124_interfaces_789.json
  test/fixtures/linode_instances_124_interfaces_settings.json
  test/fixtures/linode_instances_124_upgrade-interfaces.json
  test/fixtures/networking_firewalls_123_devices.json
  test/fixtures/networking_firewalls_123_devices_456.json
  test/fixtures/networking_firewalls_settings.json
  test/fixtures/networking_firewalls_templates.json
  test/fixtures/networking_firewalls_templates_public.json
  test/fixtures/networking_firewalls_templates_vpc.json
  test/fixtures/networking_ips_127.0.0.1.json
  test/fixtures/regions.json
  test/fixtures/vpcs_123456_subnets.json
  test/fixtures/vpcs_123456_subnets_789.json
  test/integration/conftest.py
  test/integration/linode_client/test_linode_client.py
  test/integration/models/account/test_account.py
  test/integration/models/firewall/test_firewall_templates.py
  test/integration/models/linode/interfaces/test_interfaces.py
  test/integration/models/linode/test_linode.py
  test/integration/models/networking/test_networking.py
  test/unit/groups/linode_test.py
  test/unit/groups/networking_test.py
  test/unit/linode_client_test.py
  test/unit/objects/account_test.py
  test/unit/objects/firewall_test.py
  test/unit/objects/linode_interface_test.py
  test/unit/objects/linode_test.py
  test/unit/objects/networking_test.py
  test/unit/objects/region_test.py
  test/unit/objects/serializable_test.py
  test/unit/objects/vpc_test.py
Labels: project

#603 Fix firewall device for linode interfaces
  linode_api4/objects/networking.py
  test/unit/linode_client_test.py
Labels: bugfix
