Repository linode/linode_api4-python, pull requests merged in 2025-05, with the labels that each got.

#527 Added support for DB Configurable Params
  linode_api4/groups/database.py
  linode_api4/objects/database.py
  linode_api4/objects/serializable.py
  test/fixtures/databases_mysql_config.json
  test/fixtures/databases_mysql_instances.json
  test/fixtures/databases_postgresql_config.json
  test/fixtures/databases_postgresql_instances.json
  test/integration/models/database/helpers.py
  test/integration/models/database/test_database.py
  test/integration/models/database/test_database_engine_config.py
  test/unit/groups/database_test.py
  test/unit/objects/database_test.py
Labels: new-feature

#532 Added support for Host/VM Maintenance
  linode_api4/groups/__init__.py
  linode_api4/groups/account.py
  linode_api4/groups/linode.py
  linode_api4/groups/maintenance.py
  linode_api4/linode_client.py
  linode_api4/objects/account.py
  linode_api4/objects/linode.py
  test/fixtures/account_events_123.json
  test/fixtures/account_maintenance.json
  test/fixtures/account_settings.json
  test/fixtures/linode_instances.json
  test/fixtures/maintenance_policies.json
  test/unit/groups/linode_test.py
  test/unit/linode_client_test.py
  test/unit/objects/account_test.py
  test/unit/objects/linode_test.py
Labels: new-feature

#536 Trusted publisher for PyPI
  .github/workflows/publish-pypi.yaml
Labels: repo-ci-improvement

#535 Add Object Storage Quotas integration tests
  test/integration/models/object_storage/test_obj_quotas.py
Labels: testing

#542 fix: Add / prefix to path in mysql_config_options(...) and postgresql_config_options(...) API calls
  linode_api4/groups/database.py
Labels: bugfix

#541 Configurable DB Params: Add test coverage for nullable fields
  test/integration/models/database/helpers.py
  test/integration/models/database/test_database_engine_config.py
Labels: testing

#544 Project: Limits Visibility M1
  linode_api4/groups/object_storage.py
  linode_api4/objects/object_storage.py
  test/fixtures/object-storage_quotas.json
  test/fixtures/object-storage_quotas_obj-objects-us-ord-1.json
  test/fixtures/object-storage_quotas_obj-objects-us-ord-1_usage.json
  test/integration/models/object_storage/test_obj_quotas.py
  test/unit/objects/object_storage_test.py
Labels: project

#546 Update lke node pool encryption test assertion
  test/integration/models/lke/test_lke.py
Labels: testing

#547 Improve Object Storage Quota test
  test/integration/models/object_storage/test_obj_quotas.py
Labels: testing

#533 Enhanced Interfaces: Add support for Linode-related endpoints and fields
  linode_api4/groups/linode.py
  linode_api4/groups/networking.py
  linode_api4/objects/__init__.py
  linode_api4/objects/base.py
  linode_api4/objects/linode.py
  linode_api4/objects/linode_interfaces.py
  linode_api4/objects/networking.py
  test/fixtures/linode_instances.json
  test/fixtures/linode_instances_124.json
  test/fixtures/linode_instances_124_interfaces.json
  test/fixtures/linode_instances_124_interfaces_123.json
  test/fixtures/linode_instances_124_interfaces_123_firewalls.json
  test/fixtures/linode_instances_124_interfaces_456.json
  test/fixtures/linode_instances_124_interfaces_789.json
  test/fixtures/linode_instances_124_interfaces_settings.json
  test/fixtures/linode_instances_124_upgrade-interfaces.json
  test/integration/conftest.py
  test/integration/models/linode/interfaces/test_interfaces.py
  test/integration/models/linode/test_linode.py
  test/unit/groups/linode_test.py
  test/unit/objects/linode_interface_test.py
  test/unit/objects/linode_test.py
Labels: new-feature

#550 Drop LA and v4beta notice for Limits Visibility
  linode_api4/objects/object_storage.py
Labels: documentation

#553 Proj/configurable db params
  linode_api4/groups/database.py
  linode_api4/objects/database.py
  linode_api4/objects/serializable.py
  test/fixtures/databases_mysql_config.json
  test/fixtures/databases_mysql_instances.json
  test/fixtures/databases_postgresql_config.json
  test/fixtures/databases_postgresql_instances.json
  test/integration/models/database/helpers.py
  test/integration/models/database/test_database.py
  test/integration/models/database/test_database_engine_config.py
  test/unit/groups/database_test.py
  test/unit/objects/database_test.py
Labels: project

#554 Release v5.31.0
  .github/workflows/e2e-test.yml
  .github/workflows/nightly-smoke-tests.yml
  .github/workflows/release-notify-slack.yml
  linode_api4/groups/database.py
  linode_api4/objects/database.py
  linode_api4/objects/object_storage.py
  linode_api4/objects/serializable.py
  test/fixtures/databases_mysql_config.json
  test/fixtures/databases_mysql_instances.json
  test/fixtures/databases_postgresql_config.json
  test/fixtures/databases_postgresql_instances.json
  test/integration/models/database/helpers.py
  test/integration/models/database/test_database.py
  test/integration/models/database/test_database_engine_config.py
  test/unit/groups/database_test.py
  test/unit/objects/database_test.py
Labels: ignore-for-release

#555 Implement _serialize(...) override in NodeBalancerConfig
  linode_api4/objects/nodebalancer.py
Labels: bugfix

#549 project: UDP NodeBalancers
  linode_api4/objects/nodebalancer.py
  test/fixtures/nodebalancers_123456_configs.json
  test/fixtures/nodebalancers_123456_configs_65432_nodes.json
  test/integration/models/nodebalancer/test_nodebalancer.py
  test/unit/objects/nodebalancers_test.py
Labels: project
